"""add analysis table

Revision ID: 47b63b3d240e
Revises: f1c76e675d43
Create Date: 2026-09-03 16:29:09.586812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47b63b3d240e'
down_revision: Union[str, Sequence[str], None] = 'f1c76e675d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROFILING_QUALITY', 'BUILDING_AI_CONTEXT', 'AI_ANALYZING', 'GENERATING_RECOMMENDATIONS', 'VALIDATING', 'RANKING', 'GENERATING_PREVIEWS', 'READY', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('pipeline_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('data_quality', sa.JSON(), nullable=True),
    sa.Column('ai_findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_dataset_id'), 'analyses', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analyses_dataset_version_id'), 'analyses', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_dataset_version_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_dataset_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
