/**
 * Chart type registry -- the full 41-type visualization library. Mirrors
 * `backend/app/visualization/registry.py` exactly (same ids, same `implemented` flags).
 *
 * "renderer" says which engine draws this chart type. Everything implemented so far is
 * "vega-lite" -- a generic, spec-driven engine (P16-008). Chart types requiring D3 (network
 * layouts, force-directed graphs, Sankey flow algorithms, geo projections with real topojson)
 * or a dedicated component (KPI card, data table, sparkline) are marked accordingly and
 * `implemented: false` until that renderer actually exists -- a registry entry alone is never
 * treated as "done" (see the visualization-library verification report).
 */

export type ChartCategory =
  | "comparison"
  | "temporal"
  | "distribution"
  | "relationship"
  | "part_to_whole"
  | "geographic"
  | "hierarchical"
  | "specialized"
  | "single_metric"
  | "raw_data"
  | "flow";

export type RendererEngine = "d3" | "vega-lite" | "component" | "map";

export type EncodingChannel = "x" | "y" | "color" | "size" | "detail";

export interface ChartTypeDefinition {
  id: string;
  label: string;
  category: ChartCategory;
  subcategory: string;
  description: string;
  renderer: RendererEngine;
  requiredEncodings: EncodingChannel[];
  optionalEncodings: EncodingChannel[];
  supportedFieldTypes: string[];
  minDataPoints: number;
  maxPracticalCardinality: number | null;
  supportedAggregations: string[];
  requiresTemporal: boolean;
  requiresGeographic: boolean;
  requiresHierarchical: boolean;
  requiresRelational: boolean;
  requiresOHLC: boolean;
  implemented: boolean;
  /** Why it's not implemented yet, when applicable -- never silently blank. */
  blockedReason?: string;
}

const AGG_BASIC = ["count", "sum", "mean", "median", "min", "max"];

export const CHART_REGISTRY: ChartTypeDefinition[] = [
  // ---- Magnitude comparison ----
  {
    id: "bar",
    label: "Column Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Vertical bars comparing a measure across categories.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 1,
    maxPracticalCardinality: 30,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "stacked_bar",
    label: "Stacked Column Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Column chart with an additive subgroup stacked within each category.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y", "color"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: 15,
    supportedAggregations: ["count", "sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "grouped_bar",
    label: "Bar Chart (grouped)",
    category: "comparison",
    subcategory: "magnitude",
    description: "Grouped bars comparing a measure across categories and a subgroup.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y", "color"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: 15,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "horizontal_bar",
    label: "Bar Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Horizontal bars -- automatically preferable to a column chart once category count/label length grows.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 1,
    maxPracticalCardinality: 40,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "stacked_bar_horizontal",
    label: "Stacked Bar Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Horizontally-stacked bars -- a distinct orientation from Stacked Column, not a style variant.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y", "color"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: 20,
    supportedAggregations: ["count", "sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "lollipop",
    label: "Lollipop Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Category-to-value stems with an endpoint marker, an alternative to bar for sparse rankings.",
    renderer: "d3",
    requiredEncodings: ["x", "y"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: 25,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "No D3 renderer built yet -- would be a thin stem+point variant of bar, not started this session.",
  },
  {
    id: "radar",
    label: "Radar / Spider Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Multiple metrics on a shared polar scale, comparing one or more entities.",
    renderer: "d3",
    requiredEncodings: ["detail", "size"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 3,
    maxPracticalCardinality: 8,
    supportedAggregations: ["mean", "sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Vega-Lite has no native polar/radial coordinate system; needs a custom D3 projection. Not built.",
  },
  {
    id: "bullet",
    label: "Bullet Chart",
    category: "comparison",
    subcategory: "magnitude",
    description: "Actual value vs. target with qualitative range bands (poor/average/good), for KPI-vs-target analysis.",
    renderer: "d3",
    requiredEncodings: ["x"],
    optionalEncodings: [],
    supportedFieldTypes: ["numeric", "currency"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "mean"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs a dedicated D3 component for the range-band + target-tick geometry. Not built.",
  },

  // ---- Time & trends ----
  {
    id: "line",
    label: "Line Chart",
    category: "temporal",
    subcategory: "trend",
    description: "One or more series over an ordered temporal dimension.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["date", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: null,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "area",
    label: "Area Chart",
    category: "temporal",
    subcategory: "trend",
    description: "Line chart with the area under the curve filled in; supports stacking.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["date", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: null,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "sparkline",
    label: "Sparkline Chart",
    category: "temporal",
    subcategory: "trend",
    description: "Compact, axis-free inline trend line for a single metric -- for KPI cards and table cells.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: [],
    supportedFieldTypes: ["date", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "mean"],
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "candlestick",
    label: "Candlestick Chart",
    category: "temporal",
    subcategory: "financial",
    description: "OHLC market data per period, rendered as filled candle bodies with high/low wicks.",
    renderer: "d3",
    requiredEncodings: ["x"],
    optionalEncodings: [],
    supportedFieldTypes: ["date", "numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: [],
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: true,
    implemented: false,
    blockedReason: "Needs open/high/low/close encoding support the current VisualizationSpec/compiler doesn't have (only x/y/color/size/detail), plus a D3 or Vega-Lite rule+bar layer for the candle geometry. Not built.",
  },
  {
    id: "ohlc",
    label: "Open-High-Low-Close Chart",
    category: "temporal",
    subcategory: "financial",
    description: "OHLC market data per period, rendered as tick marks (distinct geometry from candlestick).",
    renderer: "d3",
    requiredEncodings: ["x"],
    optionalEncodings: [],
    supportedFieldTypes: ["date", "numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: [],
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: true,
    implemented: false,
    blockedReason: "Same OHLC-encoding gap as candlestick; deliberately kept a separate registry entry per the spec since the tick-mark geometry is genuinely different, not just a style variant.",
  },

  // ---- Rankings ----
  {
    id: "ribbon",
    label: "Ribbon Chart",
    category: "temporal",
    subcategory: "ranking",
    description: "Ranked categories over time, connected by flowing ribbons showing rank movement.",
    renderer: "d3",
    requiredEncodings: ["x", "y", "color"],
    optionalEncodings: [],
    supportedFieldTypes: ["date", "categorical", "numeric"],
    minDataPoints: 4,
    maxPracticalCardinality: 10,
    supportedAggregations: ["sum", "mean"],
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs a custom D3 ribbon/stream layout. Not built.",
  },
  {
    id: "bump",
    label: "Bump Chart",
    category: "temporal",
    subcategory: "ranking",
    description: "Rank (not raw value) of each entity plotted over time -- how rankings change.",
    renderer: "d3",
    requiredEncodings: ["x", "y", "color"],
    optionalEncodings: [],
    supportedFieldTypes: ["date", "categorical", "numeric"],
    minDataPoints: 4,
    maxPracticalCardinality: 10,
    supportedAggregations: [],
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Requires a rank-transform (converting raw values to per-period rank) not implemented in the deterministic transform layer yet, plus a D3 line layout on the rank axis. Not built.",
  },
  {
    id: "sorted_bar",
    label: "Sorted Bar Chart",
    category: "comparison",
    subcategory: "ranking",
    description: "Bar chart explicitly sorted by measure (ascending/descending/top-N/bottom-N) as a distinct ranking mode, not incidental sort order.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: 30,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },

  // ---- Dual metrics ----
  {
    id: "line_column",
    label: "Line and Column Chart",
    category: "comparison",
    subcategory: "dual_metric",
    description: "Combination chart: one measure as columns, a second (different scale) as an overlaid line.",
    renderer: "d3",
    requiredEncodings: ["x", "y", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "date", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: 20,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "VisualizationSpec has no second-measure/dual-axis encoding concept yet -- needs a schema extension, not just a renderer. Not built.",
  },

  // ---- Part-to-whole ----
  {
    id: "donut",
    label: "Donut Chart",
    category: "part_to_whole",
    subcategory: "part_to_whole",
    description: "Part-to-whole composition as arc segments with a hollow center.",
    renderer: "vega-lite",
    requiredEncodings: ["color", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 7,
    supportedAggregations: ["sum", "count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "pie",
    label: "Pie Chart",
    category: "part_to_whole",
    subcategory: "part_to_whole",
    description: "Part-to-whole composition as filled arc segments.",
    renderer: "vega-lite",
    requiredEncodings: ["color", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 7,
    supportedAggregations: ["sum", "count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "treemap",
    label: "Treemap",
    category: "hierarchical",
    subcategory: "hierarchical",
    description: "Nested rectangles sized by a quantitative measure, grouped by a hierarchy.",
    renderer: "d3",
    requiredEncodings: ["size", "color"],
    optionalEncodings: ["detail"],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 50,
    supportedAggregations: ["sum", "count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: true,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs d3-hierarchy's squarified-treemap algorithm; d3 isn't wired into the renderer path yet despite being a project dependency. Not built.",
  },
  {
    id: "sunburst",
    label: "Sunburst Chart",
    category: "hierarchical",
    subcategory: "hierarchical",
    description: "Radial hierarchy, each ring a level of nesting.",
    renderer: "d3",
    requiredEncodings: ["size", "color"],
    optionalEncodings: ["detail"],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 50,
    supportedAggregations: ["sum", "count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: true,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Same d3-hierarchy + radial-partition dependency as treemap. Not built.",
  },

  // ---- Cumulative totals ----
  {
    id: "waterfall",
    label: "Waterfall Chart",
    category: "part_to_whole",
    subcategory: "cumulative",
    description: "Starting value, sequential positive/negative changes, and ending value, positioned by running cumulative total.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["categorical", "numeric", "currency"],
    minDataPoints: 2,
    maxPracticalCardinality: 20,
    supportedAggregations: ["sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },

  // ---- Data spread ----
  {
    id: "histogram",
    label: "Histogram",
    category: "distribution",
    subcategory: "distribution",
    description: "Binned frequency distribution of a numeric field.",
    renderer: "vega-lite",
    requiredEncodings: ["x"],
    optionalEncodings: [],
    supportedFieldTypes: ["numeric", "currency"],
    minDataPoints: 5,
    maxPracticalCardinality: null,
    supportedAggregations: ["count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "box_plot",
    label: "Box and Whisker Plot",
    category: "distribution",
    subcategory: "distribution",
    description: "Quartile summary (min, Q1, median, Q3, max, outliers), optionally grouped by category.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 5,
    maxPracticalCardinality: 20,
    supportedAggregations: [],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "violin",
    label: "Violin Plot",
    category: "distribution",
    subcategory: "distribution",
    description: "Kernel-density-estimated distribution shape, optionally grouped by category.",
    renderer: "d3",
    requiredEncodings: ["x", "y"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 10,
    maxPracticalCardinality: 12,
    supportedAggregations: [],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs a deterministic KDE (kernel density estimation) implementation -- no statistics library for this is installed, and a naive/incorrect density estimate would violate the 'mathematically correct or not implemented' rule. Not built.",
  },
  {
    id: "marimekko",
    label: "Marimekko / Mosaic Chart",
    category: "distribution",
    subcategory: "multi_dimensional",
    description: "Two categorical dimensions encoded as variable-width AND variable-height segments (area = value).",
    renderer: "d3",
    requiredEncodings: ["x", "y", "size"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 4,
    maxPracticalCardinality: 10,
    supportedAggregations: ["sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs a true variable-width-column layout (Vega-Lite bars are fixed-width); requires custom D3 geometry to avoid being 'just a stacked bar' per the spec's explicit warning. Not built.",
  },

  // ---- Correlation ----
  {
    id: "scatter",
    label: "Scatter Plot",
    category: "relationship",
    subcategory: "correlation",
    description: "Two numeric fields plotted as points to reveal correlation.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color", "size"],
    supportedFieldTypes: ["numeric", "currency"],
    minDataPoints: 5,
    maxPracticalCardinality: null,
    supportedAggregations: [],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "bubble",
    label: "Bubble Chart",
    category: "relationship",
    subcategory: "correlation",
    description: "Scatter plot with a third quantitative dimension encoded as bubble area (never radius, to keep magnitude perception linear).",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y", "size"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["numeric", "currency"],
    minDataPoints: 3,
    maxPracticalCardinality: null,
    supportedAggregations: [],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "heatmap",
    label: "Heatmap / Matrix",
    category: "relationship",
    subcategory: "correlation",
    description: "Two categorical dimensions with a numeric value encoded as cell color -- also used for correlation matrices.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y", "color"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 40,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },

  // ---- Connections / flow ----
  {
    id: "network",
    label: "Network Diagram",
    category: "relationship",
    subcategory: "connections",
    description: "Nodes and weighted edges (source/target/weight) with a force-directed or similar layout.",
    renderer: "d3",
    requiredEncodings: ["detail"],
    optionalEncodings: ["size"],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 200,
    supportedAggregations: [],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: true,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs d3-force (or equivalent) for a controlled, deterministic graph layout. Not built.",
  },
  {
    id: "chord",
    label: "Chord Diagram",
    category: "relationship",
    subcategory: "connections",
    description: "Circular arrangement of entities with weighted flows between them.",
    renderer: "d3",
    requiredEncodings: ["detail", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 20,
    supportedAggregations: ["sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: true,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs d3-chord's layout algorithm for correct proportional arc geometry. Not built.",
  },
  {
    id: "sankey",
    label: "Sankey Diagram",
    category: "flow",
    subcategory: "process",
    description: "Directional, weighted flow between stages (source/target/value), width proportional to value.",
    renderer: "d3",
    requiredEncodings: ["detail", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 30,
    supportedAggregations: ["sum"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: true,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs d3-sankey's node-positioning and link-width algorithm; a naive layout would produce incorrect flow widths, which the spec explicitly treats as a bug, not a shippable partial implementation.",
  },
  {
    id: "funnel",
    label: "Funnel Chart",
    category: "flow",
    subcategory: "process",
    description: "Ordered process stages with monotonically-decreasing values, trapezoid width proportional to value.",
    renderer: "d3",
    requiredEncodings: ["x", "y"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 10,
    supportedAggregations: ["sum", "count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "True funnel geometry is trapezoids, not bars -- Vega-Lite has no trapezoid mark. Rendering it as a sorted bar chart would misrepresent the shape (Rule 61: mathematically/visually incorrect = not implemented). Needs a small custom D3/SVG path renderer. Not built.",
  },
  {
    id: "gantt",
    label: "Gantt Chart",
    category: "flow",
    subcategory: "process",
    description: "Task bars positioned by start/end date on a temporal axis, optionally grouped.",
    renderer: "vega-lite",
    requiredEncodings: ["x", "y"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["date", "categorical"],
    minDataPoints: 1,
    maxPracticalCardinality: 50,
    supportedAggregations: [],
    requiresTemporal: true,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs a start+end date-range encoding (x and x2) the current VisualizationSpec/Encodings type doesn't support -- schema extension required, not just a renderer. Not built.",
  },
  {
    id: "decomposition_tree",
    label: "Decomposition Tree",
    category: "hierarchical",
    subcategory: "root_cause",
    description: "Interactive drill-down from a root metric through successive dimension breakdowns.",
    renderer: "d3",
    requiredEncodings: ["detail", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "count", "mean"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: true,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs interactive-expansion state management plus a hierarchy layout; the deterministic decomposition-path logic itself isn't built. Not built.",
  },

  // ---- Geospatial ----
  {
    id: "choropleth",
    label: "Choropleth / Filled Map",
    category: "geographic",
    subcategory: "mapping",
    description: "Geographic regions filled by color according to a quantitative value.",
    renderer: "map",
    requiredEncodings: ["color"],
    optionalEncodings: [],
    supportedFieldTypes: ["geographic", "numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "mean", "count"],
    requiresTemporal: false,
    requiresGeographic: true,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs region-boundary geometry (topojson) and a map projection library -- no geo-mapping dependency is installed. Not built.",
  },
  {
    id: "bubble_map",
    label: "Bubble Map Chart",
    category: "geographic",
    subcategory: "mapping",
    description: "Proportional bubbles at latitude/longitude coordinates.",
    renderer: "map",
    requiredEncodings: ["size"],
    optionalEncodings: ["color"],
    supportedFieldTypes: ["geographic", "numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "count"],
    requiresTemporal: false,
    requiresGeographic: true,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Same map-base-layer dependency gap as choropleth. Not built.",
  },
  {
    id: "flow_map",
    label: "Flow Map",
    category: "geographic",
    subcategory: "mapping",
    description: "Directional, weighted lines between origin/destination geographic coordinates.",
    renderer: "map",
    requiredEncodings: ["detail", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["geographic", "numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum"],
    requiresTemporal: false,
    requiresGeographic: true,
    requiresHierarchical: false,
    requiresRelational: true,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Same map-base-layer dependency gap as choropleth, plus great-circle path geometry. Not built.",
  },

  // ---- Single metrics ----
  {
    id: "kpi",
    label: "KPI Card",
    category: "single_metric",
    subcategory: "single_metric",
    description: "Primary value with a period-over-period comparison, change indicator, and optional inline sparkline.",
    renderer: "component",
    requiredEncodings: ["size"],
    optionalEncodings: ["x"],
    supportedFieldTypes: ["numeric", "currency"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "mean", "count"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "gauge",
    label: "Gauge",
    category: "single_metric",
    subcategory: "single_metric",
    description: "Value within a bounded min/max range, with an optional target and threshold bands.",
    renderer: "d3",
    requiredEncodings: ["size"],
    optionalEncodings: [],
    supportedFieldTypes: ["numeric"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: ["sum", "mean"],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs a D3 arc component with threshold-band geometry, plus a min/max/target encoding VisualizationSpec doesn't have yet. Not built.",
  },

  // ---- Raw data ----
  {
    id: "table",
    label: "Data Table",
    category: "raw_data",
    subcategory: "raw_data",
    description: "Sortable, paginated tabular view of the underlying rows.",
    renderer: "component",
    requiredEncodings: [],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric", "date", "text", "currency", "geographic", "identifier", "boolean"],
    minDataPoints: 1,
    maxPracticalCardinality: null,
    supportedAggregations: [],
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: true,
  },
  {
    id: "matrix",
    label: "Matrix",
    category: "raw_data",
    subcategory: "raw_data",
    description: "Row/column cross-tabulation with aggregated values, subtotals, and conditional formatting.",
    renderer: "component",
    requiredEncodings: ["x", "y", "size"],
    optionalEncodings: [],
    supportedFieldTypes: ["categorical", "numeric"],
    minDataPoints: 2,
    maxPracticalCardinality: 40,
    supportedAggregations: AGG_BASIC,
    requiresTemporal: false,
    requiresGeographic: false,
    requiresHierarchical: false,
    requiresRelational: false,
    requiresOHLC: false,
    implemented: false,
    blockedReason: "Needs pivot/cross-tab computation (row x column aggregation) plus subtotal logic that doesn't exist in the transform layer yet. Distinct from the heatmap (which is display-only, no pivoting). Not built.",
  },
];

export function getChartDefinition(chartType: string): ChartTypeDefinition | undefined {
  return CHART_REGISTRY.find((c) => c.id === chartType);
}

export function isImplemented(chartType: string): boolean {
  return getChartDefinition(chartType)?.implemented ?? false;
}
